/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedAuthenticatedRouteImport } from './routes/(protected)/_authenticated'
import { Route as publicUsersIndexRouteImport } from './routes/(public)/users/index'
import { Route as publicUsersUserIdRouteImport } from './routes/(public)/users/$userId'
import { Route as publicauthLoginRouteImport } from './routes/(public)/(auth)/login'
import { Route as protectedAuthenticatedProfileIndexRouteImport } from './routes/(protected)/_authenticated/profile/index'
import { Route as protectedAuthenticatedDashboardIndexRouteImport } from './routes/(protected)/_authenticated/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAuthenticatedRoute = protectedAuthenticatedRouteImport.update({
  id: '/(protected)/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const publicUsersIndexRoute = publicUsersIndexRouteImport.update({
  id: '/(public)/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicUsersUserIdRoute = publicUsersUserIdRouteImport.update({
  id: '/(public)/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthLoginRoute = publicauthLoginRouteImport.update({
  id: '/(public)/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAuthenticatedProfileIndexRoute =
  protectedAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)
const protectedAuthenticatedDashboardIndexRoute =
  protectedAuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => protectedAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicauthLoginRoute
  '/users/$userId': typeof publicUsersUserIdRoute
  '/users/': typeof publicUsersIndexRoute
  '/dashboard/': typeof protectedAuthenticatedDashboardIndexRoute
  '/profile/': typeof protectedAuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicauthLoginRoute
  '/users/$userId': typeof publicUsersUserIdRoute
  '/users': typeof publicUsersIndexRoute
  '/dashboard': typeof protectedAuthenticatedDashboardIndexRoute
  '/profile': typeof protectedAuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)/_authenticated': typeof protectedAuthenticatedRouteWithChildren
  '/(public)/(auth)/login': typeof publicauthLoginRoute
  '/(public)/users/$userId': typeof publicUsersUserIdRoute
  '/(public)/users/': typeof publicUsersIndexRoute
  '/(protected)/_authenticated/dashboard/': typeof protectedAuthenticatedDashboardIndexRoute
  '/(protected)/_authenticated/profile/': typeof protectedAuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/users/$userId'
    | '/users/'
    | '/dashboard/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/users/$userId' | '/users' | '/dashboard' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/(protected)/_authenticated'
    | '/(public)/(auth)/login'
    | '/(public)/users/$userId'
    | '/(public)/users/'
    | '/(protected)/_authenticated/dashboard/'
    | '/(protected)/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedAuthenticatedRoute: typeof protectedAuthenticatedRouteWithChildren
  publicauthLoginRoute: typeof publicauthLoginRoute
  publicUsersUserIdRoute: typeof publicUsersUserIdRoute
  publicUsersIndexRoute: typeof publicUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_authenticated': {
      id: '/(protected)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/users/': {
      id: '/(public)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof publicUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/users/$userId': {
      id: '/(public)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof publicUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/login': {
      id: '/(public)/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_authenticated/profile/': {
      id: '/(protected)/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof protectedAuthenticatedProfileIndexRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
    '/(protected)/_authenticated/dashboard/': {
      id: '/(protected)/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof protectedAuthenticatedRoute
    }
  }
}

interface protectedAuthenticatedRouteChildren {
  protectedAuthenticatedDashboardIndexRoute: typeof protectedAuthenticatedDashboardIndexRoute
  protectedAuthenticatedProfileIndexRoute: typeof protectedAuthenticatedProfileIndexRoute
}

const protectedAuthenticatedRouteChildren: protectedAuthenticatedRouteChildren =
  {
    protectedAuthenticatedDashboardIndexRoute:
      protectedAuthenticatedDashboardIndexRoute,
    protectedAuthenticatedProfileIndexRoute:
      protectedAuthenticatedProfileIndexRoute,
  }

const protectedAuthenticatedRouteWithChildren =
  protectedAuthenticatedRoute._addFileChildren(
    protectedAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedAuthenticatedRoute: protectedAuthenticatedRouteWithChildren,
  publicauthLoginRoute: publicauthLoginRoute,
  publicUsersUserIdRoute: publicUsersUserIdRoute,
  publicUsersIndexRoute: publicUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
